name: Build All Binaries with pkg

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install pkg
        run: npm install -g pkg

      - name: Build all binaries with pkg
        run: |
          npx pkg ./bin/edp.js --out-dir dist --targets node18-linux-x64,node18-win-x64,node18-macos-x64

      - name: Zip all binaries
        run: |
          cd dist
          zip edp-cli-binaries.zip *

    
      - name: Upload zipped binaries
        uses: actions/upload-artifact@v4
        with:
          name: edp-cli-all-platforms
          path: dist/edp-cli-binaries.zip

      - name: Commit binaries to repo
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          git pull
          mkdir -p binaries/${{ matrix.os }}
          cp dist/* binaries/${{ matrix.os }}/
          git add binaries/
          git commit -m "Add compiled binaries for ${{ matrix.os }}"
          git push
